import { StyleSheet } from "react-native";
import { palette, spacing, type } from "../../design-system/theme";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: palette.paper,
  },
  guidedStepBody: {
    paddingHorizontal: spacing.lg,
    gap: spacing.md,
    paddingBottom: spacing.xl,
  },
  guidedStepBodyUnified: {
    paddingHorizontal: 0,
    gap: spacing.md,
    paddingBottom: spacing.lg,
  },
  unifiedStageBodyCompact: {
    gap: spacing.md,
  },
  guidedBreathPanel: {
    gap: spacing.lg,
  },
  guidedBreathVisual: {
    minHeight: 284,
    borderWidth: 2,
    borderColor: palette.inkFocus,
    backgroundColor: palette.panelSoft,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  guidedBreathGrid: {
    position: "absolute",
    top: 18,
    right: 18,
    bottom: 18,
    left: 18,
    borderWidth: 1,
    borderColor: palette.outline,
  },
  guidedBreathCore: {
    width: 172,
    height: 172,
    borderWidth: 4,
    borderColor: palette.inkFocus,
    backgroundColor: palette.paper,
    alignItems: "center",
    justifyContent: "center",
  },
  guidedBreathCoreActive: {
    backgroundColor: palette.line,
  },
  guidedBreathText: {
    color: palette.peach,
    fontSize: 14,
  },
  guidedReadoutRow: {
    flexDirection: "row",
    gap: spacing.md,
  },
  guidedCopyBlock: {
    gap: spacing.md,
  },
  guidedQuote: {
    color: palette.ink,
    fontSize: 18,
    lineHeight: 30,
    fontFamily: type.bodyMedium,
  },
  guidedAudioPanel: {
    gap: spacing.lg,
  },
  guidedAudioHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.lg,
  },
  guidedPlayButton: {
    width: 72,
    height: 72,
    borderWidth: 2,
    borderColor: palette.inkFocus,
    backgroundColor: palette.line,
    alignItems: "center",
    justifyContent: "center",
  },
  guidedPlayLabel: {
    color: palette.paper,
    fontSize: 20,
  },
  guidedAudioMeta: {
    color: palette.inkMuted,
    fontSize: 10,
    letterSpacing: 0.7,
    textTransform: "uppercase",
  },
  guidedProgressTrack: {
    height: 14,
    borderWidth: 2,
    borderColor: palette.inkFocus,
    backgroundColor: palette.paper,
  },
  guidedProgressFill: {
    height: "100%",
    backgroundColor: palette.line,
  },
  guidedTranscriptHighlight: {
    borderWidth: 2,
    borderColor: palette.inkFocus,
    backgroundColor: palette.paper,
    padding: spacing.md,
    gap: spacing.xs,
  },
  guidedTranscriptTitle: {
    fontSize: 24,
    lineHeight: 28,
  },
  guidedPromptPanel: {
    gap: spacing.md,
  },
  guidedPromptTitle: {
    fontSize: 28,
    lineHeight: 34,
    textTransform: "uppercase",
  },
  guidedConstraintGrid: {
    flexDirection: "row",
    gap: spacing.md,
  },
  guidedRecorderPanel: {
    alignItems: "center",
    gap: spacing.lg,
  },
  guidedRecordButton: {
    width: 112,
    height: 112,
  },
  guidedMetricsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.md,
  },
  guidedMetricTile: {
    flexGrow: 1,
    flexBasis: "30%",
    gap: spacing.sm,
    minHeight: 104,
  },
  guidedMetricValue: {
    fontSize: 22,
    lineHeight: 26,
  },
  guidedParchmentMeta: {
    fontSize: 11,
    letterSpacing: 0.6,
    color: palette.inkMuted,
    opacity: 0.9,
    textTransform: "uppercase",
    textAlign: "center",
  },
  guidedAnalysisPanel: {
    gap: spacing.md,
  },
  guidedOverlayNotice: {
    backgroundColor: palette.line,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  guidedWavePanel: {
    gap: spacing.md,
  },
  guidedActionRow: {
    flexDirection: "row",
    gap: spacing.md,
    flexWrap: "wrap",
  },
  guidedCommitPanel: {
    gap: spacing.md,
  },
  breatheScreen: {
    backgroundColor: palette.paper,
  },
  breatheScroll: {
    flex: 1,
  },
  breatheHeader: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderBottomWidth: 2,
    borderColor: palette.inkFocus,
    backgroundColor: palette.paper,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  breatheWordmarkRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  breatheHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  breatheBrand: {
    fontFamily: type.display,
    fontSize: 20,
    color: palette.line,
    letterSpacing: -0.8,
  },
  breatheCanvas: {
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 28,
    gap: 18,
    flexGrow: 1,
  },
  sessionStrip: {
    flexDirection: "row",
    gap: 8,
  },
  sessionStripDash: {
    flex: 1,
    height: 6,
    backgroundColor: "#D9D9D9",
    borderWidth: 2,
    borderColor: palette.inkFocus,
  },
  sessionStripDashActive: {
    backgroundColor: palette.line,
  },
  progressStrip: {
    flexDirection: "row",
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  progressStripCompact: {
    marginBottom: spacing.sm,
  },
  progressStep: {
    flex: 1,
    gap: 6,
  },
  progressTrack: {
    height: 6,
    borderWidth: 1,
    borderColor: palette.inkFocus,
    backgroundColor: "#E7DDD5",
  },
  progressTrackFill: {
    width: "0%",
    height: "100%",
  },
  progressTrackFillActive: {
    width: "100%",
    backgroundColor: palette.line,
  },
  progressTrackFillDone: {
    backgroundColor: "#A34A21",
  },
  progressLabel: {
    fontSize: 9,
    color: palette.inkMuted,
  },
  progressLabelActive: {
    color: palette.line,
  },
  breatheMetaCard: {
    backgroundColor: palette.paper,
    shadowColor: palette.shadow,
    shadowOffset: { width: 8, height: 8 },
    shadowOpacity: 1,
    shadowRadius: 0,
  },
  breatheMetaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  breatheMetaRight: {
    alignItems: "flex-end",
  },
  breatheMetaLabel: {
    fontSize: 12,
    color: palette.inkMuted,
  },
  breatheMetaStage: {
    fontSize: 12,
    color: palette.line,
    marginTop: 4,
  },
  breatheMetaValue: {
    fontSize: 18,
    color: palette.line,
  },
  breatheInstructionCard: {
    gap: 14,
  },
  breatheInstructionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  breatheInstructionTitle: {
    fontSize: 30,
    lineHeight: 34,
    color: palette.line,
  },
  breatheInstructionCopy: {
    color: palette.ink,
  },
  breatheCenterZone: {
    minHeight: 0,
    justifyContent: "flex-start",
    alignItems: "center",
    gap: 20,
  },
  scrollContent: {
    paddingBottom: spacing.xl,
  },
  unifiedScreen: {
    backgroundColor: "#FDF6E3",
  },
  unifiedScrollContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xl,
    gap: spacing.md,
  },
  unifiedStageTitleWrap: {
    marginBottom: spacing.xs,
  },
  brutalistShadow: {
    shadowColor: palette.line,
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 0,
  },
  brutalistShadowInk: {
    shadowColor: "#2E2E2E",
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 0,
  },
  brutalistPanel: {
    borderWidth: 2,
    borderColor: palette.outline,
    backgroundColor: "#FDF6E3",
    padding: spacing.md,
    gap: spacing.sm,
  },
  brutalistPanelInk: {
    borderWidth: 2,
    borderColor: palette.inkFocus,
    backgroundColor: "#FDF6E3",
    padding: spacing.md,
    gap: spacing.sm,
  },
  stageHeadline: {
    fontSize: 20,
    lineHeight: 28,
    color: palette.black,
    textAlign: "center",
  },
  stagePullQuote: {
    fontSize: 17,
    lineHeight: 26,
    color: palette.inkMuted,
    textAlign: "center",
    fontStyle: "italic",
    maxWidth: 360,
    alignSelf: "center",
  },
  stageMetricText: {
    fontFamily: type.mono,
    fontSize: 20,
    lineHeight: 28,
    letterSpacing: 0.5,
    color: palette.black,
    textAlign: "center",
  },
  listenMainCard: {
    borderWidth: 2,
    borderColor: palette.outline,
    backgroundColor: "#FDF6E3",
    padding: spacing.sm,
    gap: spacing.sm,
  },
  listenCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  listenCardKicker: {
    fontSize: 10,
    letterSpacing: 1,
    color: palette.line,
    textTransform: "uppercase",
  },
  listenTranscriptBox: {
    borderWidth: 1,
    borderColor: palette.outline,
    backgroundColor: "rgba(239, 223, 216, 0.45)",
    padding: spacing.sm,
    gap: spacing.sm,
    maxHeight: 180,
  },
  listenInsightCard: {
    borderWidth: 2,
    borderColor: palette.outline,
    backgroundColor: palette.panelSoft,
    padding: spacing.sm,
    gap: spacing.sm,
  },
  listenQuoteCard: {
    borderWidth: 2,
    borderColor: palette.inkFocus,
    backgroundColor: palette.line,
    padding: spacing.sm,
    gap: spacing.xs,
  },
  listenQuoteText: {
    color: palette.peach,
    fontSize: 17,
    lineHeight: 26,
    fontStyle: "italic",
  },
  doConstraintCard: {
    borderWidth: 2,
    borderColor: palette.inkFocus,
    backgroundColor: "#FDF6E3",
    padding: spacing.md,
    gap: spacing.sm,
  },
  doConstraintBadge: {
    alignSelf: "flex-start",
    backgroundColor: palette.black,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  doConstraintBadgeText: {
    color: "#FDF6E3",
    fontSize: 10,
    letterSpacing: 0.8,
  },
  doPromptQuote: {
    fontSize: 18,
    lineHeight: 28,
    color: palette.black,
    fontStyle: "italic",
    borderLeftWidth: 4,
    borderLeftColor: palette.inkFocus,
    paddingLeft: spacing.sm,
  },
  doTimerDisplay: {
    fontFamily: type.mono,
    fontSize: 48,
    lineHeight: 52,
    color: palette.line,
    textAlign: "center",
  },
  doRecordButton: {
    width: 116,
    height: 116,
    borderWidth: 4,
    borderColor: palette.inkFocus,
    backgroundColor: "#FDF6E3",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 0,
  },
  seeMetricCard: {
    flexGrow: 1,
    flexBasis: "30%",
    minWidth: 100,
    minHeight: 104,
    borderWidth: 2,
    borderColor: palette.inkFocus,
    backgroundColor: palette.panelSoft,
    padding: spacing.md,
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  seeMetricValue: {
    fontFamily: type.mono,
    fontSize: 24,
    lineHeight: 28,
    color: palette.line,
  },
  commitQuoteBlock: {
    borderLeftWidth: 4,
    borderLeftColor: palette.inkFocus,
    paddingLeft: spacing.md,
    gap: spacing.sm,
  },
  commitQuoteText: {
    fontSize: 18,
    lineHeight: 26,
    color: palette.black,
    fontStyle: "italic",
  },
  centreBreathWrap: {
    width: 228,
    height: 228,
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    marginVertical: spacing.md,
  },
  centreBreathRing: {
    position: "absolute",
    width: 228,
    height: 228,
    borderRadius: 114,
    borderWidth: 2,
    borderColor: palette.siennaAccent,
  },
  centreBreathRingInner: {
    position: "absolute",
    width: 172,
    height: 172,
    borderRadius: 86,
    borderWidth: 1,
    borderColor: palette.outline,
    opacity: 0.4,
  },
  centreBreathCore: {
    backgroundColor: palette.parchmentSurface,
    padding: 16,
    zIndex: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  centreInstructionBlock: {
    alignItems: "center",
    gap: spacing.sm,
    maxWidth: 380,
    alignSelf: "center",
  },
  sessionDetailsWrap: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
  },
  sessionDetailsCard: {
    gap: spacing.sm,
  },
  sessionGuidanceWrap: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
  },
  sessionGuidanceCard: {
    paddingVertical: spacing.md,
    gap: spacing.xs,
  },
  sessionDetailsKicker: {
    fontSize: 11,
    color: palette.inkMuted,
    letterSpacing: 0.8,
  },
  sessionDetailsTitle: {
    fontSize: 28,
    lineHeight: 32,
  },
  sessionDetailsBody: {
    color: palette.inkMuted,
    fontSize: 15,
    lineHeight: 24,
  },
  guidancePanel: {
    gap: spacing.sm,
    marginTop: spacing.xs,
    paddingTop: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: palette.outline,
  },
  guidancePanelCompact: {
    gap: spacing.xs,
    marginTop: 0,
    paddingTop: 0,
    borderTopWidth: 0,
  },
  guidanceRow: {
    gap: 2,
  },
  guidanceLabel: {
    fontSize: 9,
    letterSpacing: 0.7,
    color: palette.line,
  },
  guidanceBody: {
    fontSize: 12,
    lineHeight: 18,
    color: palette.inkMuted,
  },
  guidanceAffirmation: {
    fontStyle: "italic",
    color: palette.ink,
    opacity: 0.88,
  },
  sharedProgressWrap: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
  },
  headerWordmark: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  sessionHeaderLeft: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    flexShrink: 1,
  },
  headerTitle: {
    fontSize: 30,
    lineHeight: 34,
  },
  headerMeta: {
    marginLeft: 6,
    gap: 2,
  },
  headerClock: {
    fontSize: 22,
  },
  exitButton: {
    width: 52,
    height: 52,
    borderWidth: 2,
    borderRadius: 26,
    borderColor: palette.inkFocus,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.paper,
  },
  backButton: {
    width: 52,
    height: 52,
    borderWidth: 2,
    borderRadius: 26,
    borderColor: palette.inkFocus,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.paper,
  },
  stepBody: {
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.xl,
    gap: spacing.lg,
  },
  stepMeta: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 2,
    borderColor: palette.inkFocus,
    paddingBottom: 12,
  },
  mobileMeta: {
    marginTop: spacing.sm,
  },
  breatheVisualWrap: {
    width: 280,
    height: 280,
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
  },
  breatheGuideFrame: {
    position: "absolute",
    width: 190,
    height: 190,
    borderWidth: 2,
    borderColor: "#CFCFCF",
  },
  breatheCrosshairHorizontal: {
    position: "absolute",
    width: 252,
    height: 2,
    backgroundColor: "#D6D6D6",
  },
  breatheCrosshairVertical: {
    position: "absolute",
    width: 2,
    height: 252,
    backgroundColor: "#D6D6D6",
  },
  breatheOuterRing: {
    position: "absolute",
    width: 190,
    height: 190,
    borderWidth: 4,
    borderColor: palette.inkFocus,
    backgroundColor: "rgba(255,255,255,0.82)",
    transform: [{ scale: 0.92 }],
  },
  breatheOuterRingActive: {
    transform: [{ scale: 1.02 }],
  },
  breathePulseBox: {
    position: "absolute",
    width: 112,
    height: 112,
    borderWidth: 2,
    borderColor: palette.inkFocus,
    backgroundColor: "#F0F0F0",
  },
  breatheInnerRing: {
    width: 76,
    height: 76,
    borderWidth: 4,
    borderColor: palette.inkFocus,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: palette.line,
  },
  breatheInnerRingActive: {
    transform: [{ scale: 1.08 }],
  },
  windGlyph: {
    color: palette.paper,
    fontSize: 18,
  },
  breatheCopy: {
    alignItems: "center",
    gap: 12,
    maxWidth: 300,
  },
  breatheCountLabel: {
    fontSize: 12,
    color: palette.inkMuted,
  },
  breatheCountValue: {
    fontSize: 40,
    lineHeight: 42,
    color: palette.line,
  },
  centerQuote: {
    textAlign: "center",
    fontStyle: "italic",
    color: palette.inkMuted,
  },
  breatheFooterCard: {
    backgroundColor: "#EFEDE8",
  },
  breatheFooterRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 16,
  },
  breatheFooterBlock: {
    flex: 1,
    gap: 6,
  },
  breatheFooterValue: {
    fontSize: 16,
    color: palette.line,
  },
  breatheActionArea: {
    paddingTop: 6,
  },
  listenGrid: {
    gap: spacing.lg,
  },
  listenLeftColumn: {
    gap: spacing.md,
  },
  listenRightColumn: {
    gap: spacing.md,
  },
  lessonSurface: {
    gap: spacing.lg,
  },
  lessonTopRow: {
    flexDirection: "row",
    gap: spacing.md,
  },
  lessonCardTitle: {
    fontSize: 28,
    lineHeight: 32,
  },
  liveBadge: {
    backgroundColor: palette.line,
    paddingHorizontal: 12,
    paddingVertical: 8,
    alignSelf: "flex-start",
  },
  liveBadgeText: {
    color: palette.paper,
    fontSize: 11,
  },
  waveformPanel: {
    height: 192,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 4,
  },
  waveformBar: {
    flex: 1,
    maxWidth: 4,
    borderRadius: 99,
    backgroundColor: palette.line,
  },
  audioControls: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
  },
  audioActionButton: {
    width: 46,
    height: 46,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.line,
    borderWidth: 2,
    borderColor: palette.inkFocus,
  },
  audioActionLabel: {
    color: palette.paper,
    fontSize: 18,
  },
  audioTrack: {
    flex: 1,
    height: 4,
    backgroundColor: "#D9CBB9",
    position: "relative",
  },
  audioTrackProgress: {
    height: "100%",
    backgroundColor: palette.line,
  },
  insightCard: {
    gap: spacing.sm,
  },
  insightHeading: {
    fontSize: 13,
    color: palette.line,
  },
  insightQuote: {
    color: palette.ink,
    fontStyle: "italic",
  },
  transcriptPanel: {
    minHeight: 520,
  },
  transcriptHeader: {
    backgroundColor: palette.line,
    paddingHorizontal: spacing.md,
    paddingVertical: 12,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  transcriptHeaderText: {
    color: palette.paper,
    fontSize: 11,
  },
  transcriptBody: {
    padding: spacing.md,
    gap: spacing.md,
  },
  transcriptMuted: {
    color: palette.inkMuted,
    opacity: 0.75,
  },
  transcriptHighlight: {
    backgroundColor: "#EEDFD5",
    borderLeftWidth: 3,
    borderColor: palette.inkFocus,
    padding: spacing.md,
    gap: 8,
  },
  transcriptHighlightTitle: {
    fontSize: 24,
    lineHeight: 26,
    color: palette.line,
  },
  transcriptHighlightMeta: {
    color: palette.line,
    fontSize: 10,
  },
  transcriptFocus: {
    color: palette.ink,
    fontFamily: type.bodyMedium,
  },
  transcriptFooter: {
    padding: spacing.md,
    borderTopWidth: 2,
    borderColor: palette.outline,
  },
  outlineBadge: {
    borderWidth: 2,
    borderColor: palette.inkFocus,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    alignSelf: "flex-start",
  },
  outlineBadgeText: {
    fontSize: 12,
    color: palette.line,
  },
  metricGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.md,
  },
  miniMetric: {
    width: "47%",
    gap: 8,
  },
  metricLabel: {
    fontSize: 10,
    color: palette.inkMuted,
  },
  metricValue: {
    fontSize: 30,
    color: palette.ink,
  },
  figureCard: {
    height: 220,
    overflow: "hidden",
  },
  figureArt: {
    flex: 1,
    backgroundColor: palette.black,
  },
  figureArtOverlay: {
    backgroundColor: "#3A1206",
  },
  figureTag: {
    position: "absolute",
    left: 14,
    bottom: 14,
    backgroundColor: palette.paper,
    borderWidth: 2,
    borderColor: palette.inkFocus,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  figureLabel: {
    fontSize: 10,
  },
  promptCard: {
    gap: spacing.lg,
  },
  promptBadge: {
    alignSelf: "flex-start",
    backgroundColor: palette.line,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  promptBadgeText: {
    color: palette.paper,
    fontSize: 11,
  },
  promptTitle: {
    fontSize: 38,
    lineHeight: 44,
  },
  remainingLabel: {
    textAlign: "center",
    fontSize: 14,
  },
  timerDisplay: {
    textAlign: "center",
    fontSize: 58,
    lineHeight: 62,
  },
  timerAlert: {
    color: "#BA1A1A",
  },
  recordButtonWrap: {
    width: 196,
    height: 196,
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
  },
  recordPulseRing: {
    position: "absolute",
    width: 148,
    height: 148,
    borderRadius: 999,
    borderWidth: 4,
    borderColor: "rgba(124,45,18,0.22)",
  },
  recordPulseRingActive: {
    transform: [{ scale: 1.05 }],
  },
  recordPulseRingLarge: {
    position: "absolute",
    width: 176,
    height: 176,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: "rgba(124,45,18,0.12)",
  },
  recordPulseRingLargeActive: {
    transform: [{ scale: 1.08 }],
  },
  recordButtonCore: {
    width: 128,
    height: 128,
    borderRadius: 999,
    backgroundColor: palette.line,
    justifyContent: "center",
    alignItems: "center",
  },
  recordingMeta: {
    textAlign: "center",
    fontSize: 16,
    color: palette.line,
  },
  waveRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "flex-end",
    gap: 6,
    minHeight: 68,
  },
  waveColumn: {
    width: 6,
    backgroundColor: palette.line,
  },
  badgeDark: {
    alignSelf: "flex-start",
    backgroundColor: palette.line,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  badgeDarkText: {
    color: palette.paper,
  },
  feedbackTitle: {
    fontSize: 52,
    lineHeight: 52,
  },
  divider: {
    height: 2,
    backgroundColor: palette.line,
  },
  feedbackMetrics: {
    gap: spacing.md,
  },
  metricCard: {
    gap: spacing.md,
  },
  metricWide: {},
  metricNarrow: {},
  metricFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  metricBig: {
    fontSize: 48,
    lineHeight: 50,
  },
  metricFoot: {
    color: palette.inkMuted,
    fontSize: 10,
  },
  quoteBox: {
    gap: spacing.md,
  },
  commentaryQuote: {
    color: palette.line,
    fontStyle: "italic",
    fontSize: 24,
    lineHeight: 32,
  },
  feedbackActions: {
    gap: spacing.md,
  },
  environmentRow: {
    gap: spacing.md,
  },
  environmentFigure: {
    height: 190,
    position: "relative",
    overflow: "hidden",
  },
  environmentBadge: {
    position: "absolute",
    left: 14,
    bottom: 14,
    backgroundColor: palette.paper,
    borderWidth: 2,
    borderColor: palette.inkFocus,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  environmentCopy: {
    borderLeftWidth: 3,
    borderColor: palette.inkFocus,
    paddingLeft: spacing.md,
  },
  commitMetaBar: {
    marginTop: spacing.sm,
    backgroundColor: "#EEE0CC",
    borderTopWidth: 2,
    borderBottomWidth: 2,
    borderColor: palette.inkFocus,
    paddingHorizontal: spacing.lg,
    paddingVertical: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  commitMetaChunk: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  commitMetaLabel: {
    fontSize: 10,
    color: palette.line,
  },
  commitStepBadge: {
    backgroundColor: palette.line,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  commitStepBadgeText: {
    color: palette.paper,
  },
  commitTimerValue: {
    color: palette.line,
  },
  reflectHeader: {
    gap: 8,
  },
  reflectKicker: {
    marginTop: spacing.md,
    fontSize: 14,
    color: palette.line,
  },
  reflectTitle: {
    fontSize: 40,
    lineHeight: 42,
  },
  reflectRecorder: {
    gap: spacing.md,
  },
  reflectTopBar: {
    borderWidth: 2,
    borderColor: palette.inkFocus,
    height: 44,
    position: "relative",
    overflow: "hidden",
  },
  reflectProgress: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    backgroundColor: palette.line,
  },
  reflectTopLabels: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: spacing.md,
  },
  reflectTopLabel: {
    color: palette.paper,
    mixBlendMode: "difference",
  },
  tapRecordWrap: {
    alignItems: "center",
    gap: spacing.md,
  },
  tapRecordButton: {
    width: 112,
    height: 112,
    borderRadius: 999,
    backgroundColor: palette.line,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 7,
    borderColor: palette.paper,
  },
  tapRecordLabel: {
    fontSize: 14,
  },
  suggestedOpener: {
    gap: spacing.sm,
  },
  suggestedHeadingRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  suggestedHeading: {
    color: palette.peach,
    fontSize: 12,
  },
  suggestedCopy: {
    color: palette.peach,
    fontStyle: "italic",
    fontSize: 17,
    lineHeight: 26,
  },
});
